package com.example.trello.dto;

public enum SuccessCode {
    FIND_CATEGORY_SUCCESS, GET_ALL_CATEGORY_SUCCESS, ADD_CATEGORY_SUCCESS, UPDATE_CATEGORY_SUCCESS, DELETE_CATEGORY_SUCCESS,
    FIND_PRODUCT_SUCCESS, GET_ALL_PRODUCT_SUCCESS, ADD_PRODUCT_SUCCESS, UPDATE_PRODUCT_SUCCESS, DELETE_PRODUCT_SUCCESS,
    FIND_USER_SUCCESS, GET_ALL_USER_SUCCESS, ADD_USER_SUCCESS, UPDATE_USER_SUCCESS, DELETE_USER_SUCCESS,

}
